import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Flight Sim Airport Lookup",
    template: "%s – Flight Sim Airport Lookup",
  },
  description:
    "Flight simulator airport lookup with runways, lighting, frequencies and navaids. Reference only – not for real-world navigation.",
  applicationName: "Flight Sim Airport Lookup",
  generator: "Flight Sim Airport Lookup – generated by MM23",
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
